### ISSUE TITLE
What prevents opencv4 from being supported via setup.py?

### ISSUE THREAD

**Issue by olirice** [edmBernard/pybind11_opencv_numpy#15]
Could you please explain why opencv4 isn't compatible with the existing setup.py installation approach?

Very cool project

**Comment by edmBernard** [comment]
just some work I think, I haven't really try as I don't use this approach much.
But if it's needed I can search a bit to enable it.

**Comment by edmBernard** [comment]
the issue is the opencv include directory change between 
- opencv 3+ : `opencv2/core.h`
- opencv4 : `opencv4/opencv2/core.h`
I'll try to fix the installation process later

**Comment by edmBernard** [comment]
to build with opencv4 I only find this solution : 
```
python3 setup.py build_ext --include-dirs "/usr/local/include/opencv4"
python3 setup.py install
```

**Comment by edmBernard** [comment]
I update the doc with the extra step for opencv4
https://github.com/edmBernard/pybind11_opencv_numpy#opencv4

**Comment by olirice** [comment]
That's great, thank you!

This
```
python setup.py build_ext --include_dirs "/usr/local/include/opencv4"
```
is giving me an error `error: option --include_dirs not recognized`

but adding that directory directly here
https://github.com/edmBernard/pybind11_opencv_numpy/blob/1e8f280382630a0eeead2fd3c2c048a2ae184265/setup.py#L96
worked

**Comment by edmBernard** [comment]
yeah it as the same effect
I think you miss spell `--include-dirs` not `--include_dirs`
I'm glad it work for you
