### ISSUE TITLE
binding for std::vector<cv::Mat>

### ISSUE THREAD

**Issue by thancaocuong** [edmBernard/pybind11_opencv_numpy#17]
I've tried but failed. Could you tell me how should I do? thank for your awesome work

**Comment by edmBernard** [comment]
The conversion between std::vector<cv::Mat> and cv::Mat list is automatic. To enable it don't forget to include `pybind11/stl.h`
https://github.com/edmBernard/pybind11_opencv_numpy/issues/3#issuecomment-330030905
