### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by hstarmans** [edmBernard/pybind11_opencv_numpy#18]
I used your code to wrap a c++ camera library; see https://github.com/hstarmans/Arducampython.
In this code, I call get image a lot. This results in a memory leak.
I have now fixed this by handling the lifetime of the image pointer in C++.
```
cv::Mat *Camera::pythoncapture(uint32_t exptime)
{
    // data is sent over to python, you need to explicitly clear it
    // if capture is called directly; this results in a memory leak 
    if(pyimage != NULL){delete pyimage;}
    pyimage = capture(exptime);
    return  pyimage;
}
```
If I call this method from python i use;
```
.def("capture", &Camera::pythoncapture, py::return_value_policy::copy, "Capture image with given exposure time and return buffer", py::arg("exptime"))
```
See pybind documentation on [functions](https://pybind11.readthedocs.io/en/stable/advanced/functions.html). I tried other policies, they all lead to a memory leak. Using  &Camera::capture directly leads to a memory leak as well.

**Comment by edmBernard** [comment]
I quickly check your code. 
In `capture` you create a new image and return the pointer on it. So each time you call capture it will recreate a new image without releasing the previous one. 
I see 2 solutions
  1- use an internal image member in the capture class that you will fill in capture and release in the destructor of camera
  2- maybe a smart pointer (unique_ptr and a move or shared_ptr) will do the job

I personnaly prefer the first solution, it reduce memory allocation as you replace existing image. (and I'm almost sure it will work)

**Comment by hstarmans** [comment]
Option one is close to the solution I currently use. Pyimage is a member of the camera class. If there is already an image, i.e. pointer is not NULL, it gets deleted by the camera class. I don't think that release should be called from python. As this is not Pythonic. I had hoped Pybind would somehow handle this automatically. But my knowledge of C++ is too limited. Now I copy, the image to the Python side so I have two instances which can live separate lives.
The point is that in your example, probably read image also results in a memory leak.  Maybe later i will try to write an example to proof it or invalidate my assumption.

**Comment by edmBernard** [comment]
In my example I don't use pointer so It should not have memory leak.

In your code, the delete added in pythoncapture don't remove the memory leak but minimise it.
You should implemente a destructor of your `Camera` class and in this destructor add a delete of pyimage.

**Comment by edmBernard** [comment]
I try to put my idea on a fork of your project 
https://github.com/hstarmans/Arducampython/compare/master...edmBernard:master

for a less C code and a more C++. You could add constructor and destructor to manage the internal open close etc ... I put this track here https://github.com/hstarmans/Arducampython/compare/master...edmBernard:dev/more_cpp_style
I can't test if it compile

**Comment by hstarmans** [comment]
Did a test; your library does not have this problem. So issue is purely related to my implementation, guess you get the :1st_place_medal:  :-)

**Comment by hstarmans** [comment]
Note, I have also fixed my library and now do not pass a pointer but the image, as you do.
