### ISSUE TITLE
OpenCV 2.4 isn't supported

### ISSUE THREAD

**Issue by elazarcoh** [edmBernard/pybind11_opencv_numpy#26]
Hi,
Thanks for sharing this utility.
I just wanted to note that OpenCV 2.4 isn't supported anymore. e.g. `UMatData` is an `OpenCV >= 3` type.

**Comment by edmBernard** [comment]
thanks, you are right, the numpy allocation is really done differently on opencv 2.4. 
I think I can remove opencv 2.4 from the documentation, You're the first person to notice this in 5 years.
