### ISSUE TITLE
how to return a list of cvMat?

### ISSUE THREAD

**Issue by KeyKy** [edmBernard/pybind11_opencv_numpy#3]

**Comment by KeyKy** [comment]
Thanks!

**Comment by edmBernard** [comment]
If you return a `std::vector<cv::Mat>` and don't forget  `#include <pybind11/stl.h>` .
The conversion in python list is automatic.

**Comment by KeyKy** [comment]
Great thanks!

**Comment by thancaocuong** [comment]
@edmBernard  thank you, I've solved that problem 👍
