### ISSUE TITLE
'numpy/ndarrayobject.h' file not found

### ISSUE THREAD

**Issue by wangpeiguo** [edmBernard/pybind11_opencv_numpy#6]
When I execute python setup.py install, generate a error(ndarray_converter.cpp:7:10: fatal error: 'numpy/ndarrayobject.h' file not found).
How should I solve it?

**Comment by edmBernard** [comment]
@wangpeiguo did you have numpy (the python library) install on your computer ?

**Comment by wangpeiguo** [comment]
Yes. I have solved it. Thanks.
