### ISSUE TITLE
Which Version Of Opencv is Supported?

### ISSUE THREAD

**Issue by StartingnewDJW** [edmBernard/pybind11_opencv_numpy#7]
the convertion between numpy and c++ cv::Mat. which opencv version does this project support? and aslo support with multithread operation (using the conversion in child thread)?

**Comment by edmBernard** [comment]
opencv 2.4 and 3+
I haven't try opencv 4 yet.
For the multithread part, I don't think I understand you question.
You want to execute a c++("binded") function in separate thread.

**Comment by edmBernard** [comment]
@StartingnewDJW Have you been able to solve your issue ?

**Comment by edmBernard** [comment]
Closed due to inactivity
